all:
  children:
    web:
      hosts:
        server-one:
          ansible_host: ec2-34-211-172-152.us-west-2.compute.amazonaws.com
        server-two:
          ansible_host: ec2-54-218-114-205.us-west-2.compute.amazonaws.com
